<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bangsal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bangsal_model');
    } 

    /*
     * Listing of bangsal
     */
    function index()
    {
        $data['bangsal'] = $this->Bangsal_model->get_all_bangsal();
        
        $data['_view'] = 'bangsal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bangsal
     */
    function add()
    {  
        $this->load->library('form_validation');
        $this->form_validation->set_rules('kd_bangsal', 'Kode Bangsal', 'required');
        $this->form_validation->set_rules('nm_bangsal', 'Nama Bangsal', 'required');
        $this->form_validation->set_rules('status', 'Status', 'required');
        $this->form_validation->run() == FALSE;
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nm_bangsal' => $this->input->post('nm_bangsal'),
				'status' => $this->input->post('status'),
            );
            
            $bangsal_id = $this->Bangsal_model->add_bangsal($params);
            redirect('bangsal/index');
        }
        else
        {            
            $data['_view'] = 'bangsal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bangsal
     */
    function edit($kd_bangsal)
    {   
        // check if the bangsal exists before trying to edit it
        $data['bangsal'] = $this->Bangsal_model->get_bangsal($kd_bangsal);
        
        if(isset($data['bangsal']['kd_bangsal']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nm_bangsal' => $this->input->post('nm_bangsal'),
					'status' => $this->input->post('status'),
                );

                $this->Bangsal_model->update_bangsal($kd_bangsal,$params);            
                redirect('bangsal/index');
            }
            else
            {
                $data['_view'] = 'bangsal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bangsal you are trying to edit does not exist.');
    } 

    /*
     * Deleting bangsal
     */
    function remove($kd_bangsal)
    {
        $bangsal = $this->Bangsal_model->get_bangsal($kd_bangsal);

        // check if the bangsal exists before trying to delete it
        if(isset($bangsal['kd_bangsal']))
        {
            $this->Bangsal_model->delete_bangsal($kd_bangsal);
            redirect('bangsal/index');
        }
        else
            show_error('The bangsal you are trying to delete does not exist.');
    }

      public function export(){
        // Skrip berikut ini adalah skrip yang bertugas untuk meng-export data tadi ke excel
        header("Content-type: application/vnd-ms-excel");
        header("Content-Disposition: attachment; filename=Bangsal_Rumah_Sakit.xls");
        
        $data['bangsal'] = $this->Bangsal_model->get_all_bangsal();
        $this->load->view('bangsal/export', $data);
      }

            
    function get_data_user()
    {
        $list = $this->Bangsal_model->get_datatables();
        $data = array();
        $no = $_POST['start'];
        foreach ($list as $bangsal) {
            $no++;
            $row = array();
            $row[] = $bangsal->kd_bangsal;
            $row[] = $bangsal->nm_bangsal;
            $row[] = $bangsal->status;
            $row[] = '<a href="bangsal/edit/'.$bangsal->kd_bangsal.'" class="btn btn-info btn-xs">Edit</a> 
            <a href="bangsal/remove/'.$bangsal->kd_bangsal.'" class="btn btn-danger btn-xs">Delete</a>';
            $data[] = $row;
        }

        $output = array(
            "draw" => $_POST['draw'],
            "recordsTotal" => $this->Bangsal_model->count_all(),
            "recordsFiltered" => $this->Bangsal_model->count_filtered(),
            "data" => $data,
        );
        //output dalam format JSON
        echo json_encode($output);
    }

}
