<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Master_triase_macam_kasu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Master_triase_macam_kasu_model');
    } 

    /*
     * Listing of master_triase_macam_kasus
     */
    function index()
    {
        $data['master_triase_macam_kasus'] = $this->Master_triase_macam_kasu_model->get_all_master_triase_macam_kasus();
        
        $data['_view'] = 'master_triase_macam_kasu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new master_triase_macam_kasu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'macam_kasus' => $this->input->post('macam_kasus'),
            );
            
            $master_triase_macam_kasu_id = $this->Master_triase_macam_kasu_model->add_master_triase_macam_kasu($params);
            redirect('master_triase_macam_kasu/index');
        }
        else
        {            
            $data['_view'] = 'master_triase_macam_kasu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a master_triase_macam_kasu
     */
    function edit($kode_kasus)
    {   
        // check if the master_triase_macam_kasu exists before trying to edit it
        $data['master_triase_macam_kasu'] = $this->Master_triase_macam_kasu_model->get_master_triase_macam_kasu($kode_kasus);
        
        if(isset($data['master_triase_macam_kasu']['kode_kasus']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'macam_kasus' => $this->input->post('macam_kasus'),
                );

                $this->Master_triase_macam_kasu_model->update_master_triase_macam_kasu($kode_kasus,$params);            
                redirect('master_triase_macam_kasu/index');
            }
            else
            {
                $data['_view'] = 'master_triase_macam_kasu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The master_triase_macam_kasu you are trying to edit does not exist.');
    } 

    /*
     * Deleting master_triase_macam_kasu
     */
    function remove($kode_kasus)
    {
        $master_triase_macam_kasu = $this->Master_triase_macam_kasu_model->get_master_triase_macam_kasu($kode_kasus);

        // check if the master_triase_macam_kasu exists before trying to delete it
        if(isset($master_triase_macam_kasu['kode_kasus']))
        {
            $this->Master_triase_macam_kasu_model->delete_master_triase_macam_kasu($kode_kasus);
            redirect('master_triase_macam_kasu/index');
        }
        else
            show_error('The master_triase_macam_kasu you are trying to delete does not exist.');
    }
    
}
