<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Master_triase_macam_kasu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get master_triase_macam_kasu by kode_kasus
     */
    function get_master_triase_macam_kasu($kode_kasus)
    {
        return $this->db->get_where('master_triase_macam_kasus',array('kode_kasus'=>$kode_kasus))->row_array();
    }
        
    /*
     * Get all master_triase_macam_kasus
     */
    function get_all_master_triase_macam_kasus()
    {
        $this->db->order_by('kode_kasus', 'desc');
        return $this->db->get('master_triase_macam_kasus')->result_array();
    }
        
    /*
     * function to add new master_triase_macam_kasu
     */
    function add_master_triase_macam_kasu($params)
    {
        $this->db->insert('master_triase_macam_kasus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update master_triase_macam_kasu
     */
    function update_master_triase_macam_kasu($kode_kasus,$params)
    {
        $this->db->where('kode_kasus',$kode_kasus);
        return $this->db->update('master_triase_macam_kasus',$params);
    }
    
    /*
     * function to delete master_triase_macam_kasu
     */
    function delete_master_triase_macam_kasu($kode_kasus)
    {
        return $this->db->delete('master_triase_macam_kasus',array('kode_kasus'=>$kode_kasus));
    }
}
